name: Build host tools

on:
  push:

jobs:
  build:
    name: tools-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: 
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: openwrt

      - name: Setup Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            build-essential \
            ccache \
            clang-12 \
            ecj \
            fastjar \
            file \
            g++ \
            gawk \
            gettext \
            git \
            java-propose-classpath \
            libelf-dev \
            libncurses-dev \
            libssl-dev \
            mkisofs \
            python3 \
            python3-dev \
            python3-distutils \
            python3-setuptools \
            qemu-utils \
            rsync \
            subversion \
            swig \
            unzip \
            wget \
            xsltproc \
            zlib1g-dev
          echo "WORKPATH=$GITHUB_WORKSPACE/openwrt/" >> "$GITHUB_ENV"
          cd "$WORKPATH"
          pwd

      - name: Make prereq
        run: |
          cd "$WORKPATH"
          pwd
          echo "CONFIG_ALL=y" >> "$WORKPATH/.config"
          make defconfig

      - name: Build OpenWrt
        run: |
          cd "$WORKPATH"
          make -j1 V=s BUILD_LOG=1

      - name: Move logs to GITHUB_WORKSPACE
        if: always()
        run: |
          cp -r "$WORKPATH/logs" "$GITHUB_WORKSPACE"
          cp -r "$WORKPATH/.config" "$GITHUB_WORKSPACE/config"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-logs
          path: "logs"

      - name: Upload config
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-config
          path: "config"
